[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-plugin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }
versions = { id = "io.github.ben-manes.versions", version.ref = "versions-plugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "catalog-update-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin" }

[versions]
spotless-plugin = "8.9.0"
lombok-plugin = "9.5.0"
versions-plugin = "0.61.0"
catalog-update-plugin = "1.1.1"
shadow-plugin = "9.6.1"
h2 = "2.4.240"
hikaricp = "7.1.0"
jackson = "2.22.1"
commons-text = "1.15.0"
jte = "3.2.4"
slf4j = "2.0.18"
javalin = "7.2.3"
assertj = "3.27.7"
junit-bom = "6.1.3"

[libraries]
# Database
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hikariCp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
# Jackson
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
# Web
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
javalinBundle = { module = "io.javalin:javalin-bundle", version.ref = "javalin" }
javalinRenderingJte = { module = "io.javalin:javalin-rendering-jte", version.ref = "javalin" }
jte = { module = "gg.jte:jte", version.ref = "jte" }
# Utilities
commonsText = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
# Tests
assertjCore = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
